my_blog/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list,name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article-safe-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),

]

my_blog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 二级评论
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/',views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/',views.CommentNoticeUpdateView.as_view(),name='update'),

]

my_blog/userprofile/urls.py
from django.urls import path,include
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    #path('password-reset/', include('password_reset.urls')),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image


class ArticleColumn(models.Model):
    # 栏目的model
    title = models.CharField(max_length=100,blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    # 作者 设置on_delete 级联删除
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    # 标题
    title = models.CharField(max_length=100)
    # 正文
    body = models.TextField()
    # 文章创建时间
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间
    updated = models.DateTimeField(auto_now=True)
    # 浏览量
    total_views = models.PositiveIntegerField(default=0)
    # 标签
    tags = TaggableManager(blank=True)
    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)

    def save(self, *args,**kwargs):
        article = super(ArticlePost,self).save(*args,**kwargs)
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x,y) = image.size
            new_x = 400
            new_y = int(new_x*(y/x))
            resized_image = image.resize((new_x,new_y),Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article


    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        # 设置以倒叙排序
        ordering = ('-created',)
    def __str__(self):
        # 返回文章标题
        return self.title
    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

my_blog/article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据的来源
        model = ArticlePost
        fields = ('title','body','tags','avatar')

my_blog/article/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from .models import ArticlePost
import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from .models import ArticleColumn
from comment.forms import CommentForm
from django.shortcuts import get_object_or_404

def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = ArticlePost.objects.all()

    # if request.GET.get('order') == 'total_views':
    #     article_list = ArticlePost.objects.all().order_by('-total_views')
    #     order = 'total_views'
    # else:
    #     article_list = ArticlePost.objects.all()
    #     order = 'normal'
    #
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

        # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

        # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

        # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 需要传递给模板（templates）的对象
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }

    return render(request, 'article/list.html', context)

def article_detail(request,id):
    # article = ArticlePost.objects.get(id=id)
    article = get_object_or_404(ArticlePost, id=id)


    article.total_views += 1
    article.save(update_fields=['total_views'])
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)
    comments = Comment.objects.filter(article=id)
    comment_form = CommentForm()
    context = {'article': article, 'toc': md.toc,'comment_form':comment_form,'comments':comments}

    return render(request,'article/detail.html',context)

@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST,request.FILES)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据 但暂时不提交在数据库中
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])

            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写")
    else:
        # 创建表单实例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context={'article_post_form':article_post_form,'columns': columns}
        return render(request,'article/create.html',context)

def article_delete(request,id):
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect("article:article_list")

def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

@login_required(login_url='/userprofile/login/')
def article_update(request,id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title=request.POST['title']
            article.body=request.POST['body']
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            article.save()
            return redirect("article:article_detail",id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context={'article':article,'article_post_form':article_post_form,'columns':columns}
        return render(request,'article/update.html',context,)

my_blog/templates/article/create.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 写文章 {% endblock title %}

{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章标题图 -->
    <div class="form-group">
        <label for="avatar">标题图</label>
        <input type="file" class="form-control-file" name="avatar" id="avatar">
    </div>
                 <!-- 文章标签 -->
                <div class="form-group">
            <label for="tags">标签</label>
            <input type="text"
               class="form-control col-3"
               id="tags"
               name="tags"
                 >
                </div>
                 <!-- 文章栏目 -->
                 <div class="form-group">
            <label for="column">栏目</label>
            <select class="form-control"
                id="column"
                name="column"
        >
                <option value="none">请选择栏目..</option>
            {% for column in columns %}
                <option value="{{ column.id }}">{{ column }}</option>
            {% endfor %}
        </select>
    </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    文章详情
{% endblock title %}

{% block script %}
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

{% endblock script %}

{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0);
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>

<!-- 文章详情 -->
<div class="container">

    <div class="row">
        <!-- 标题及作者 -->
        <div class="col-9">
        <h1 class="col-9 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-9 alert alert-success">作者：{{ article.author }}
            {% if user == article.author %}
<!--        ·<a href="#" onclick="confirm_delete()">删除文章</a>-->
            · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
            · <a href="{% url 'article:article_update' article.id %}">
                        编辑文章
                    </a>
            <br>
            浏览：{{ article.total_views }}

             {% endif %}
            </div>


            <form
      style="display:none;"
      id="safe_delete"
      action="{% url 'article:article_safe_delete' article.id %}"
      method="POST"
      >
    {% csrf_token %}
    <button type="submit">发送</button>
</form>
            <!-- 发表评论 -->


            </div>
<!--        <div class="col-3 mt-4">-->
<!--            <h4><strong>目录</strong></h4>-->
<!--            <hr>-->
<!--            <div>-->
<!--                {{ toc|safe }}-->
<!--            </div>-->
<!--        </div>-->
        <!-- 目录 -->
<div ... id="sidebar" class="sidebar">
    <div class="sidebar__inner">
        <h4><strong>目录</strong></h4>
        <hr>
        <div>
            {{ toc|safe }}
        </div>
    </div>
</div>


        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        <hr>
    {% if user.is_authenticated %}
        <div>
            <form
                action="{% url 'comment:post_comment' article.id %}"
                method="POST"
            >
            {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            我也要发言：
                        </strong>
                    </label>
<!--                    <textarea-->
<!--                        type="text"-->
<!--                        class="form-control"-->
<!--                        id="body"-->
<!--                        name="body"-->
<!--                        rows="2"></textarea>-->
                    <div>
            {{ comment_form.media }}
            {{ comment_form.body }}
        </div>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary ">发送</button>
            </form>
        </div>
        <br>
    {% else %}
        <br>
        <h5 class="row justify-content-center">
            请<a href="{% url 'userprofile:login' %}">登录</a>后回复
        </h5>
        <br>
    {% endif %}



<!--     显示评论-->
<!--    <h4>共有{{ comments.count }}条评论</h4>-->
<!--    <div>-->
<!--        {% for comment in comments %}-->
<!--            <hr>-->
<!--            <p>-->
<!--                <strong style="color: pink">-->
<!--                    {{ comment.user }}-->
<!--                </strong> 于-->
<!--                <span style="color: green">-->
<!--                    {{ comment.created|date:"Y-m-d H:i:s" }}-->
<!--                </span> 时说：-->
<!--            </p>-->
<!--            <pre style="font-family: inherit; font-size: 1em;">-->
<!--{{ comment.body|safe }}</pre>-->
<!--        {% endfor %}-->
<!--    </div>-->
{% load mptt_tags %}
<h4>共有{{ comments.count }}条评论</h4>
<div class="row">
    <!-- 遍历树形结构 -->
    {% recursetree comments %}
        <!-- 给 node 取个别名 comment -->
        {% with comment=node %}



                <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}"
                            id="comment_elem_{{ comment.id }}"
                        >

                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong>

                    {% if comment.reply_to %}
                        <i class="far fa-arrow-alt-circle-right"
                           style="color: cornflowerblue;"
                        ></i>对
                        <strong style="color: pink">
                            {{ comment.reply_to }}
                        </strong>
                    {% endif %}

                </p>
                <div>
                    {{ comment.body|safe }}</div>

                <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                    <!-- 加载 modal 的按钮 -->
                    {% if user.is_authenticated %}
                    <button type="button"
                            class="btn btn-light btn-sm text-muted"
                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                            >
                        回复
                    </button>
                    {% else %}
                    <a class="btn btn-light btn-sm text-muted"
                       href="{% url 'userprofile:login' %}"
                       >
                        回复
                    </a>
                    {% endif %}
                </div>

                <!-- Modal -->
                <div class="modal fade"
                     id="comment_{{ comment.id }}"
                     tabindex="-1"
                     role="dialog"
                     aria-labelledby="CommentModalCenter"
                     aria-hidden="true"
                >
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content" style="height: 480px">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                            </div>
                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                        </div>

                    </div>
                </div>

                {% if not comment.is_leaf_node %}
                    <div class="children">
                        {{ children }}
                    </div>
                {% endif %}
            </div>


        {% endwith %}
    {% endrecursetree %}
</div>


<!--原            -->
</div>
        </div>
    </div>


<script>
    // function confirm_delete() {
    //     // 调用layer弹窗组件
    //     layer.open({
    //         // 弹窗标题
    //         title: "确认删除",
    //         // 正文
    //         content: "确认删除这篇文章吗？",
    //         // 点击确定按钮后调用的回调函数
    //         yes: function(index, layero) {
    //             // 指定应当前往的 url
    //             location.href='{% url "article:article_delete" article.id %}'
    //         },
    //     })}
    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗？",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }

</script>

<script>
    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' +
                article_id +
                '/' +
                comment_id +
                '"' +
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                comment_id +
                '"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    }
</script>

{% endblock content %}

my_blog/templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
            首页
    {% endblock title %}

{% block content %}
<!-- 定义放置文章标题的div容器 -->

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">
                    最热
                </a>
            </li>
        </ol>
    </nav>
    <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                    required
                >
                <button type="submit" class="btn btn-primary">搜索</button>
            </form>
        </div>
    </div>

    <!-- 新增，搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}

    <div class="row mt-2">
<!--        v1.0 卡片容器 但由于后期增加标签 卡片容器难以满足后续需求 故改进-->
<!--        {% for article in articles %}-->
<!--        <div class="col-4 mb-4">-->
<!--        &lt;!&ndash; 卡片容器 &ndash;&gt;-->
<!--            <div class="card h-100">-->
<!--                &lt;!&ndash; 标题 &ndash;&gt;-->
<!--                <h4 class="card-header">{{ article.title }}</h4>-->
<!--                &lt;!&ndash; 摘要 &ndash;&gt;-->
<!--                <div class="card-body">-->
<!--                    <p class="card-text">{{ article.body|slice:'100' }}...</p>-->
<!--                </div>-->
<!--                &lt;!&ndash; 注脚 &ndash;&gt;-->
<!--                <div class="card-footer">-->
<!--                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>-->
<!--                    <span>-->
<!--                        <small class="col align-self-end" style="color: gray;">-->
<!--                            浏览：{{article.total_views}}-->

<!--                        </small>-->
<!--                    </span>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% endfor %}-->
 {% for article in articles %}
        <!-- 标题图 -->
        {% if article.avatar %}
            <div class="col-3">
                <img src="{{ article.avatar.url }}"
                     alt="avatar"
                     style="max-width:100%; border-radius: 20px"
                >
            </div>
        {% endif %}

        <!-- 文章内容 -->
        <div class="col">
            <!-- 栏目 -->
            {% if article.column %}
                <a  role="button"
                        href="{% url 'article:article_list' %}?column={{ article.column.id }}"
                    class="btn btn-sm mb-2
                        {% if article.column.title == 'python' %}
                            btn-success
                        {% elif article.column.title == 'java' %a}
                            btn-danger
                        {% elif article.column.title == 'c' %}
                            btn-warning
                        {% endif %}a
                    "
                >
                    {{ article.column }}
                </a>
            {% endif %}

            <!-- 标签 -->
<span>
    {% for tag in article.tags.all %}
        <a href="{% url 'article:article_list' %}?tag={{ tag }}"
           class="badge badge-secondary"
        >
            {{ tag }}
        </a>
    {% endfor %}
</span>

            <!-- 标题 -->
            <h4>
                <b>
                    <a href="{% url 'article:article_detail' article.id %}"
                       style="color: black;"
                    >
                        {{ article.title }}
                    </a>
                </b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                    <!-- 附加信息 -->
                    <span>
                        <i class="fas fa-eye" style="color: lightskyblue;"></i>
                        {{ article.total_views }}&nbsp;&nbsp;&nbsp;
                    </span>
                    <span>
                        <i class="fas fa-comments" style="color: yellowgreen;"></i>
                        {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                    </span>
                    <span>
        <i class="fas fa-clock" style="color: pink;"></i>
        {{ article.created|date:'Y-m-d' }}
    </span>
                </p>
            <hr>
        </div>
        <hr style="width: 100%;"/>
    {% endfor %}

    </div>




    <div class="row mt-2">
        {% for article in articles %}

        {% endfor %}
</div>
<!-- 页码导航 -->
<div class="pagination row">
    <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
<!--                <a href="?page=1" class="btn btn-success">-->
<!--                    &laquo; 1-->
<!--                </a>-->
            <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">&laquo; 1</a>
                <span>...</span>
<!--                <a href="?page={{ articles.previous_page_number }}"-->
<!--                   class="btn btn-secondary"-->
<!--                >-->
            <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
   class="btn btn-secondary">
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
<!--                <a href="?page={{ articles.next_page_number }}"-->
<!--                   class="btn btn-secondary"-->
<!--                >-->
            <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
   class="btn btn-secondary">
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
<!--                <a href="?page={{ articles.paginator.num_pages }}"-->
<!--                   class="btn btn-success"-->
<!--                >-->
            <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
   class="btn btn-success">{{ articles.paginator.num_pages }} &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

my_blog/templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                <!-- 文章栏目 -->
    <div class="form-group">
        <label for="column">栏目</label>
        <select class="form-control"
                id="column"
                name="column"
        >
                <option value="none">请选择栏目..</option>
            {% for column in columns %}
                <option value="{{ column.id }}"
                    {% if column.id == article.column.id %}
                        selected
                    {% endif %}
                >
                    {{ column }}
                </option>
            {% endfor %}
        </select>
    </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}