my_blog/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list,name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article-safe-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),

]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/',views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/',views.CommentNoticeUpdateView.as_view(),name='update'),

]

my_blog/userprofile/urls.py
from django.urls import path,include
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    #path('password-reset/', include('password_reset.urls')),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/templates/back_to_top_func.html
<!-- Author: 鹦鹉 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

my_blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<!--    <link rel="stylesheet"-->
<!--      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"-->
<!--      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"-->
<!--      crossorigin="anonymous"-->
<!--&gt;-->
</head>
<body>
{% include 'header.html' %}


    <!-- 新增两个 div 容器 -->
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>

{% include 'footer.html' %}
<style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
<script src="{% static 'popper/popper-1.14.4.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
{% include 'back_to_top_func.html' %}
{% block script %}{% endblock script %}

</body>
</html>

my_blog/templates/footer.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <br><br><br>
</div>
<!-- 增加 id="footer" 属性 -->
<footer ... id="footer">
    ...
</footer>
<!--<footer class="py-3 bg-dark fixed-bottom">-->
<footer class="py-3 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.xiaoningzi.com 2020</p>
    </div>
</footer>
</body>
</html>

my_blog/templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="#">小宁子博客网</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
        </li>
         {% if user.is_authenticated %}
        <form
    style="display:none;"
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}"
    method="POST"
>
{% csrf_token %}
    <button type="submit">发送</button>
</form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                 <!-- 新增代码，小红点 -->
        {% if unread_count %}
            <svg viewBox="0 0 8 8"
                 width="8px"
                 height="8px">
                <circle cx="4"
                        cy="4"
                        r="4"
                        fill="#ff6b6b"
                        ></circle>
            </svg>
        {% endif %}

             欢迎您： {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <!-- 新增代码，通知计数 -->
        <a class="dropdown-item" href="{% url 'notice:list' %}">通知
            {% if unread_count %}
            <span class="badge badge-danger">{{ unread_count }}</span>
            {% endif %}
        </a>

                <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                 <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
            </div>
        </li>
    <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
        </li>
    <!-- if 语句在这里结束 -->
        {% endif %}

      </ul>
    </div>

  </div>
</nav>
</body>
</html>